[package]
name = "bb2_serde_ron"
version = "0.1.0"
authors = ["Pedro <pdcmpa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.92", features = ["derive"] }
ron = "0.5.1"
